server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Snippet Manager
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:snippet-manager}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}
  servlet:
    multipart:
      enabled: true

auth0:
  audience: ${AUTH0_AUDIENCE}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

services:
  printscript:
    url: ${PRINTSCRIPT_HOST:http://localhost:9090}
  asset:
    url: ${ASSET_HOST:http://localhost:8081}
  permission:
    url: ${PERMISSION_HOST:http://localhost:8082}