server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Snippet Manager
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:snippet-manager}
  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

services:
  printscript:
    url: ${PRINTSCRIPT_HOST:http://localhost:9090}