name: Continuous Deployment

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish_docker_image:
    uses: ./.github/workflows/publish_docker_image.yml@v1

  update_vm:
    uses: ./.github/workflows/deploy.yml@v1
