name: Continuous Deployment

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages Stable
        if: github.ref == 'refs/heads/main'
        id: docker_build_stable
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ingsis15/snippet-manager:latest

      - name: Push to GitHub Packages Dev
        if: github.ref == 'refs/heads/dev'
        id: docker_build_dev
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ingsis15/snippet-manager:dev

  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    environment: ${{ env.DEPLOY_ENV }}
    uses: IngSis15/infra/.github/workflows/deploy.yml@main
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    secrets:
      vm_resource_group: ${{ secrets.VM_RESOURCE_GROUP }}
      vm_name: ${{ secrets.VM_NAME }}
      vm_username: ${{ secrets.VM_USERNAME }}
      vm_ip: ${{ secrets.VM_IP }}
      ssh_key: ${{ secrets.SSH_KEY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
