name: Continuous Deployment

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages Stable
        if: github.ref == 'refs/heads/main'
        id: docker_build_stable
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ingsis15/snippet-manager:latest
          secrets: |
            github_username=${{ github.actor }}
            github_token=${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages Dev
        if: github.ref == 'refs/heads/dev'
        id: docker_build_dev
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ingsis15/snippet-manager:dev
          secrets: |
            github_username=${{ github.actor }}
            github_token=${{ secrets.GITHUB_TOKEN }}

  deploy_dev:
    name: Deploy to dev VM
    if: github.ref == 'refs/heads/dev'
    needs: push_to_registry
    uses: IngSis15/infra/.github/workflows/deploy.yml@main
    with:
      environment: "dev"
    secrets:
      vm_username: ${{ secrets.DEV_VM_USERNAME }}
      vm_ip: ${{ secrets.DEV_VM_IP }}
      ssh_key: ${{ secrets.DEV_SSH_KEY }}

  deploy_prod:
    name: Deploy to prod VM
    if: github.ref == 'refs/heads/main'
    needs: push_to_registry
    uses: IngSis15/infra/.github/workflows/deploy.yml@main
    with:
      environment: "prod"
    secrets:
      vm_username: ${{ secrets.VM_USERNAME }}
      vm_ip: ${{ secrets.VM_IP }}
      ssh_key: ${{ secrets.SSH_KEY }}
