name: Deploy Service

on:
  workflow_run:
    workflows: ["Publish Docker image to GitHub Packages"]
    types:
      - completed

jobs:
  deploy:
    uses: IngSis15/infra/.github/workflows/deploy-service.yml@main
    with:
      environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    secrets:
      vm_resource_group: ${{ secrets.VM_RESOURCE_GROUP }}
      vm_name: ${{ secrets.VM_NAME }}
      vm_username: ${{ secrets.VM_USERNAME }}
      vm_ip: ${{ secrets.VM_IP }}
      ssh_key: ${{ secrets.SSH_KEY }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
