name: Publish Docker image to GitHub Packages
on:
   workflow_call:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages Stable
        if: github.ref == 'refs/heads/main'
        id: docker_build_stable
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
           ghcr.io/ingsis15/snippet-manager:latest

      - name: Push to GitHub Packages Dev
        if: github.ref == 'refs/heads/dev'
        id: docker_build_dev
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
           ghcr.io/ingsis15/snippet-manager:dev
        
        
